# Generated by Django 4.2 on 2023-04-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0007_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='number',
            new_name='mobile_number',
        ),
    ]
