# Generated by Django 4.2 on 2023-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0008_rename_number_invoice_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
