# Generated by Django 4.2 on 2023-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0010_notications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notications',
            name='accepted',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notications',
            name='posted',
            field=models.CharField(max_length=255),
        ),
    ]
