# Generated by Django 4.2 on 2023-04-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0011_alter_notications_accepted_alter_notications_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notications',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
