# Generated by Django 4.2 on 2023-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0012_alter_notications_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('Notications_on', models.BooleanField(default=False)),
            ],
        ),
    ]
