# Generated by Django 4.2 on 2023-04-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0014_rename_whatsapp_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='user_Settings',
        ),
    ]
