# Generated by Django 4.2 on 2023-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0015_rename_settings_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_settings',
            name='emergency_number',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user_settings',
            name='select_Hospital',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
