# Generated by Django 4.2 on 2023-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0016_user_settings_emergency_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='emergency_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='select_Hospital',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
