# Generated by Django 4.2 on 2023-04-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0017_alter_user_settings_emergency_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_settings',
            name='Notications_on',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
