# Generated by Django 4.2 on 2023-04-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dharam_api', '0018_alter_user_settings_notications_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_settings',
            old_name='mobile_number',
            new_name='whatsapp_number',
        ),
    ]
